# -*- coding: utf-8 -*-
"""Jogo Zumbi

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mwgk4QNLxLScRmYk3nbViaTEiYDR8DaC
"""

# Nome: Jhonathan Alexandre Bueno
# Idade: 18 anos
# Curso: Análise e Desenvolvimento de Sistemas

import random

# Jogadores

jogadores = []

while True:
  jogador = str(input("Digite seu nome (digite Start para começar o jogo): ")).upper()
  if jogador != 'START':
    jogadores.append(jogador)
  
  elif len(jogadores) < 2 and jogador == 'START':
      print('ERRO! É necessário no mínimo 2 jogadores para iniciar.')

  else:
    break

for k, v in enumerate(jogadores):
  print(f'O jogador {k + 1} é {v} ')

# dados
dado = ['verde', 'verde', 'verde', 'verde', 'verde', 'verde', 'amarelo', 'amarelo', 'amarelo', 'amarelo', 'vermelho', 'vermelho', 'vermelho']
dado_verde = ('cerebro', 'passo', 'cerebro', 'tiro', 'passo', 'cerebro')
dado_amarelo = ('tiro', 'passo', 'cerebro', 'tiro', 'passo', 'cerebro')
dado_vermelho = ('tiro', 'passo', 'tiro', 'cerebro', 'passo', 'tiro')
cerebro = 0
passo = 0
tiro = 0
for player in jogadores:
  pontuacao =  {"jogador": player, "cerebro": cerebro, "tiro": tiro}
  print(pontuacao)

# Jogador escolhe se quer jogar ou parar
while True:
  print('')
  print(dado)
  jogar = str(input("Digite J para jogar o dado e P para parar! ")).upper().strip()[0]
  print('---------------------')
  if tiro >=3:
    print(f'Acabou seu turno! Voce levou {tiro} tiros.')
    print(f"Vez de {player}")
    tiro = 0      
    continue
  
  if cerebro >= 13:
    print("Temos um vencedor")
    break

  if jogar == 'J' and len(dado) >= 3:
    for i in range(3):
      sorteado = (random.choice(dado))
    # Dado verde
      if sorteado == 'verde':
        dado.remove('verde')
        lado = random.choice(dado_verde)
        print(f'O dado sorteado foi Verde e caiu {lado}')
        if lado == 'cerebro':
          cerebro += 1
          pontuacao["cerebro"] = cerebro
          print(f'Cerebro = {cerebro}')
          print('---------------------')

        elif lado == 'passo':
          passo += 1
          print(f'Passo = {passo}')
          print('---------------------')
        
        else:
          tiro += 1
          print(f'Tiro = {tiro}')
          print('---------------------')

      # Dado Amarelo
      elif sorteado == 'amarelo':
        dado.remove('amarelo')
        lado = random.choice(dado_amarelo)
        print(f'O dado sorteado foi Amarelo e caiu {lado}')
        if lado == 'cerebro':
          cerebro += 1
          pontuacao["cerebro"] = cerebro
          print(f'Cerebro = {cerebro}')
          print('---------------------')

        elif lado == 'passo':
          passo += 1
          print(f'Passo = {passo}')
          print('---------------------')
        
        else:
          tiro += 1
          print(f'Tiro = {tiro}')
          print('---------------------')

      # Dado Vermelho
      else:
        dado.remove('vermelho')
        lado = random.choice(dado_vermelho)
        print(f'O dado sorteado foi Vermelho e caiu {lado}')
        if lado == 'cerebro':
          cerebro += 1
          pontuacao["cerebro"] = cerebro
          print(f'Cerebro = {cerebro}')
          print('---------------------')

        elif lado == 'passo':
          passo += 1
          print(f'Passo = {passo}')
          print('---------------------')
        
        else:
          tiro += 1
          print(f'Tiro = {tiro}')
          print('---------------------')
  
  elif jogar == 'P' or len(dado) < 3:
    print('Acabou seu turno')
    tiro = 0
    print(pontuacao)
    dado = ['verde', 'verde', 'verde', 'verde', 'verde', 'verde', 'amarelo', 'amarelo', 'amarelo', 'amarelo', 'vermelho', 'vermelho', 'vermelho']
    continue

  elif jogar == "X":
    break
 
  else:
    print("Por favor, digite apenas J ou P!")